spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tourdb
    username: myuser2
    password: 6574

  jpa:
    hibernate:
      ddl-auto: update

server:
  ssl:
    key-alias: tour
    key-store: classpath:tour.jks
    key-store-password: tourapp
    key-store-type: JKS

cloudinary:
  cloud_name: drfnzmkqf
  api_key: 348329312131219
  api_secret: RyMSRpJCI1vliEo5dfVICndpc6Y