spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://viaduct.proxy.rlwy.net:23549/railway
    username: postgres
    password: dab*4FA5aeFC-5f3F6G-*eFg44f*CAAe

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 443

cloudinary:
  cloud_name: drfnzmkqf
  api_key: 348329312131219
  api_secret: RyMSRpJCI1vliEo5dfVICndpc6Y

